---
- hosts: acs
  tasks:

  - name: Create sudoers.d file
    become: yes
    file:
      path: /etc/sudoers.d/{{ ansible_user_id }}
      state: touch 

  - name: Allow current user to have passwordless sudo
    become: yes
    lineinfile:
      dest: /etc/sudoers.d/{{ ansible_user_id }}
      state: present
      regexp: '^{{ ansible_user_id }}'
      line: '{{ ansible_user_id }} ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
  
  - name: add apt keys
    become: yes
    apt_key:
      url: "{{ item }}"
      state: present 
    with_items:
    - https://dl.google.com/linux/linux_signing_key.pub
    - https://packages.microsoft.com/keys/microsoft.asc
    - https://download.docker.com/linux/ubuntu/gpg

  - name: add apt repositories
    become: yes
    apt_repository:
      repo: "{{ item }}"
      state: present
    with_items:
    - deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    - deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    - deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable

  - name: install apps
    become: yes
    apt:
      autoclean: yes
      autoremove: yes
      update_cache: yes
      name: "{{ item }}"
    with_items:
    - git
    - google-chrome-stable
    - code 
    - openjdk-8-jdk
    - libstdc++5:i386 
    - libpam0g:i386 
    - libx11-6:i386
    - docker-ce

  - name: remove duplicate repositories
    become: yes
    file:
      path: /etc/apt/sources.list.d/{{ item }} 
      state: absent
    with_items:
    - google-chrome.list
    - vscode.list

  - name: download snx script
    get_url:
      url: https://vpn.logibec.com/CSHELL/snx_install.sh
      dest: "{{ playbook_dir }}/snx_install.sh"
      mode: +x

  - name: install snx
    become: yes
    script: "{{ playbook_dir }}/snx_install.sh"
    
  - name: create docker group
    become: yes
    group:
      name: docker
      state: present

  - name: Add current user to docker group
    become: yes
    user:
      name: "{{ ansible_user_id }}"
      groups: docker
      append: yes